### ISSUE TITLE
Plugin fails to initialize with `unhandled error: interface conversion: interface {} is nil`

### ISSUE THREAD

**Issue by Priyanka-Chatterjee-2000** [turbot/steampipe-plugin-prometheus#10]
**Describe the bug**
```
steampipe-plugin-prometheus % steampipe query
Welcome to Steampipe v0.19.0-rc.10
For more information, type .help
> 
Warning: failed to start plugin 'hub.steampipe.io/plugins/turbot/prometheus@latest': failed to plugin initialise plugin 'steampipe-plugin-prometheus': TableMapFunc 'pluginTableDefinitions' had unhandled error: interface conversion: interface {} is nil, not string
```

**Steampipe version (`steampipe -v`)**
 v0.19.0-rc.10

**Plugin version (`steampipe plugin list`)**
v0.1.0

**Steampipe Plugin SDK version**
v3.3.2

**To reproduce**
Setup prometheus, configure steampipe plugin and run steampipe query. It gives a warning `TableMapFunc 'pluginTableDefinitions' had unhandled error: interface conversion: interface {} is nil, not string`.

**Comment by cbruno10** [comment]
@Priyanka-Chatterjee-2000 What Steampipe SDK version are you using when you get this error? Can you please also update the other parts of the issue description, e.g., Steampipe CLI version, plugin version, reproduce, etc.

**Comment by Priyanka-Chatterjee-2000** [comment]
Yes sure @cbruno10 I have updated the issue description with necessary details thank you !!

**Comment by cbruno10** [comment]
@Priyanka-Chatterjee-2000 Does this plugin work with the latest SDK version, v5.3.0, or do you get an error?

**Comment by Priyanka-Chatterjee-2000** [comment]
I have tested it with `steampipe-plugin-sdk v5.2.0` in branch `update-sdk-416` but I get that error there as well. No I have not added any metrics. My `prometheus.spc`:
```
connection "prometheus" {
  plugin = "prometheus"
  address = "http://localhost:9090"
  # HTTP address of your prometheus server
  # address = "http://localhost:9090"

  # List of metrics that will be considered for dynamic table creation
  # Please refer to https://prometheus.io/docs/prometheus/latest/querying/basics
  # for information about supported expressions
  # For example:
  #   - ".+" matches all metrics
  #   - "prometheus_http_request.*" matches metrics starting with "prometheus_http_request"
  #   - ".*error.*" matches metrics containing the word "error"
  metrics = [".+"]
}

```

**Comment by misraved** [comment]
Fixed in https://github.com/turbot/steampipe-plugin-prometheus/pull/9
